// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3319.MyRobot;

import org.usfirst.frc3319.MyRobot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    public Joystick stick;
    public Joystick climberStick;
	public JoystickButton gripperClose;
	public JoystickButton gripperOpen;
	public JoystickButton gripperRaise;
	public JoystickButton gripperLower;
	public JoystickButton engageHook;
	public JoystickButton engageWinch;
	public JoystickButton disengageHook;
	public JoystickButton disengageWinch;
	public JoystickButton stopElevator;

		
	//heights are negative because the up is negative on the elevator
	public static final double SWITCH_HEIGHT = -4763;
	public static final double SCALE_HEIGHT = -16275;
	public static final double DEFAULT_HEIGHT = -1500;

    public OI() {
    	
    	/*
    	 * Gripper Controls:
    	 * 		X:				Lower
    	 * 		Y:				Raise
    	 * 		LB:				Release
    	 * 		RB:				Grab
    	 * Elevator Controls:
    	 * 		POV Up:			Go to next setPoint up
    	 * 		POV Down:		Go to next setPoint down
    	 * 		Right Stick:	Up/Down manually
    	 * 		Start:			Abort Movement
    	 * DriveTrain Controls:
    	 * 		Left Stick:		Forward/Backward/Left/Right
    	 * 		LT:				Turn Left
    	 * 		RT:				Turn Right
    	 * Climber Controls:
    	 * 		A:				Engage Winch
    	 * 		B:				Disengage Winch
    	 *      Y: Engage Hook
    	 *      X: Disengage Hook
    	 */

        stick = new Joystick(0);
        climberStick = new Joystick(1);
		gripperClose = new JoystickButton(stick, 3);
		gripperOpen = new JoystickButton(stick, 4);
		gripperRaise = new JoystickButton(stick, 2);
		gripperLower = new JoystickButton(stick, 1);
		stopElevator = new JoystickButton(stick, 8);//Start Button
		
		engageWinch = new JoystickButton(climberStick, 1);//A
		disengageWinch = new JoystickButton(climberStick, 2); //B
		disengageHook = new JoystickButton(climberStick, 3);
		engageHook = new JoystickButton(climberStick, 4);
		

		
		
		gripperClose.whenPressed(new CloseGripper());
		gripperOpen.whenPressed(new OpenGripper());
		gripperRaise.whenPressed(new RaiseGripper());
		gripperLower.whenPressed(new LowerGripper());
		engageHook.whileHeld(new EngageHook());
		disengageHook.whileHeld(new DisengageHook());
		disengageWinch.whileHeld(new DisengageWinch());
		engageWinch.whileHeld(new EngageWinch());
		stopElevator.whenPressed(new DisableElevator());
		

        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand(DriverStation.getInstance().getGameSpecificMessage()));
		SmartDashboard.putData("CloseGripper", new CloseGripper());
		SmartDashboard.putData("OpenGripper", new OpenGripper());
		SmartDashboard.putData("RaiseGripper", new RaiseGripper());
		SmartDashboard.putData("LowerGripper", new LowerGripper());
		SmartDashboard.putData("ZeroEncoders", new ZeroEncoders());
		SmartDashboard.putData("RaiseSwitchHeight", new SetElevatorSetpoint(SWITCH_HEIGHT));
		SmartDashboard.putData("RaiseScaleHeight", new SetElevatorSetpoint(SCALE_HEIGHT));
		SmartDashboard.putData("LowerToDefaultHeight", new SetElevatorSetpoint(DEFAULT_HEIGHT));
		SmartDashboard.putData("TurnRight90", new TurnAngle(90, 5));
		SmartDashboard.putData("TurnLeft90", new TurnAngle(-90,5));
		SmartDashboard.putData("ZeroGyro", new ZeroGyro());
		SmartDashboard.putData("SetFrontUltrasonic", new SetUltrasonicSensor(true));
		SmartDashboard.putData("SetBackUltrasonic", new SetUltrasonicSensor(false));
		SmartDashboard.putData("Drive To 10 Inches", new DriveToInches(10, 5, true));

		
		SmartDashboard.putNumber("Drive Proportional", 0.4);
		SmartDashboard.putNumber("Drive Integral", 0.0);
		SmartDashboard.putNumber("Drive Differential", 0.75);
		
		
		SmartDashboard.putBoolean("Compressor On", false);
		SmartDashboard.putNumber("Speed Step Drive Train", Robot.DriveTrain.defaultStep);
		
		SmartDashboard.putNumber("Elevator Speed", 0);
		
    }

    public Joystick getstick() {
        return stick;
    }
    
    public double getXValue() {
    	return stick.getX();
    }
    
    public double getYValue() {
    	return stick.getY();
    }
    
    public double getAxis(int axis) {
    	return stick.getRawAxis(axis);
    }
    
    public double getRotationLeft() {
    	return stick.getRawAxis(2);
    }
    
    public double getRotationRight() {
    	return stick.getRawAxis(3);
    }
    
    public int getPOV() {
    	return stick.getPOV();
    }
    

}

