// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3319.MyRobot.subsystems;
import java.util.Arrays;

import org.usfirst.frc3319.MyRobot.Robot;
import org.usfirst.frc3319.MyRobot.RobotMap;
import org.usfirst.frc3319.MyRobot.commands.*;
import org.usfirst.frc3319.custom.ADIS16448_IMU;
import org.usfirst.frc3319.custom.Adis;
import org.usfirst.frc3319.custom.UltrasonicWrapper;

import com.github.cliftonlabs.json_simple.JsonKey;
import com.github.cliftonlabs.json_simple.JsonObject;
import com.github.cliftonlabs.json_simple.Jsoner;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.SerialPort.Port;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.SerialPort;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.drive.MecanumDrive;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import java.util.regex.*;

/**
 *
 */
public class DriveTrain extends PIDSubsystem {
	private final SpeedController leftFront = RobotMap.driveTrainLeftFront;
    private final SpeedController rightFront = RobotMap.driveTrainRightFront;
    private final SpeedController leftRear = RobotMap.driveTrainLeftRear;
    private final SpeedController rightRear = RobotMap.driveTrainRightRear;
    protected final MecanumDrive mecanumDrive = RobotMap.driveTrainMecanumDrive;
    private final Adis  gyro = RobotMap.gyro;
    protected final PIDController gyroController = RobotMap.gyroController;
    private UltrasonicWrapper ultrasonic = RobotMap.ultrasonic;
	public double defaultStep = 0.025;
	double maxPowerPID = 0.6;
	double maxPowerGyroPID = 0.5;
	private int driveTolerance = 2;
	private int gyroTolerance = 2;
	public double startTime;
	public double currentTime;
	public int maxTime = 5000;
    
	public DriveTrain() {
		super("DriveTrain", 0.5,0.0,2.0);
		setAbsoluteTolerance(driveTolerance); //Set 2 inches as the tolerance for purposes of driving
    	getPIDController().setContinuous(false);
    	setOutputRange(-maxPowerPID, maxPowerPID);
    	
    	gyroController.setContinuous(false);
    	gyroController.setOutputRange(-maxPowerGyroPID, maxPowerGyroPID); //Set turning speed output to be not more than 40% power
    	gyroController.setAbsoluteTolerance(gyroTolerance); //Set tolerance on the gyro PID for 2 degrees
    	gyroController.disable();
     }
	


    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new DriveWithJoystick());
    }
    
    @Override
    public void periodic() {

    	ultrasonic.readUltrasonicInches();
    	SmartDashboard.putNumber("Robot Heading value", getGyroValue());
    	SmartDashboard.putNumber("Gyro PID power", gyroController.get());
    	SmartDashboard.putNumber("Ultrasonic reading", getUltrasonicInches());
    }
    
    public void cartesianDrive(double xValue, double yValue, double rotationValue) {
    	//Negate xValue to resolve strafing direction issue
    	mecanumDrive.driveCartesian(-xValue, yValue, rotationValue);
    }
    
    public void stop() {
    	leftFront.stopMotor();
    	rightFront.stopMotor();
    	leftRear.stopMotor();
    	rightRear.stopMotor();
    	disable();
    	resetGyro();

    }
    
    public boolean getUltrasonicSensor() {
    	return ultrasonic.getUltrasonicSensor();
    }
    
    public void setUltrasonicSensor(boolean front) {
    	ultrasonic.setUltrasonicSensor(front);
    }
    
    public long getUltrasonicInches() {
    	return ultrasonic.getUltraSonic();
    }
    
    public double getGyroValue() {
    	return gyro.getRobotHeading();
    }
    
    public void resetGyro() {
    	gyro.reset();
    }
    
    public void calibrateGyro() {
    	gyro.calibrate();
    }

	@Override
	protected double returnPIDInput() {
		return ultrasonic.pidGet();
	}

	@Override
	protected void usePIDOutput(double output) {
		if (ultrasonic.getUltrasonicSensor()) {
			mecanumDrive.driveCartesian(0, output,0);//gyroController.get());
		} else {
			mecanumDrive.driveCartesian(0, -output, 0);//gyroController.get());
		}
	}
	
	public void setGyroSetpoint(double setpoint) {
		gyroController.setSetpoint(setpoint);
	}
	
	public double getGyroSetpoint() {
		return gyroController.getSetpoint();
	}
	
	//Only use for the purpose of turning with the gyro
	//This will not do anything for any other drive train purpose
	public void enableGyroController() {
		gyroController.enable();
	}
	
	public void disableGyroController() {
		gyroController.disable();
	}
	
	public boolean isGyroControllerOnTarget() {
		return gyroController.onTarget();
	}
	
	public void setGyroPID(double p, double i, double d) {
		gyroController.setPID(p, i, d);
	}
}

